trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
    - .gitignore
    - screenshots
    
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'QualityRelease-ND-SC'
    backendAzureRmResourceGroupName: 'tstate'
    backendAzureRmStorageAccountName: 'tstate23125'
    backendAzureRmContainerName: 'tstate'
    backendAzureRmKey: 'terraform.tfstate'